/*
 * Futures (USDⓈ-M) WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

use crate::{common::config::ConfigurationWebsocketStreams, models::WebsocketStreamsConnectConfig};

use super::{UsdMStreamConnectionScope, WebsocketStreams};

#[derive(Clone)]
pub struct WebsocketStreamsHandle {
    configuration: ConfigurationWebsocketStreams,
}

impl WebsocketStreamsHandle {
    #[must_use]
    pub fn new(configuration: ConfigurationWebsocketStreams) -> Self {
        Self { configuration }
    }

    /// Connects to a WebSocket stream using default configuration.
    ///
    /// # Returns
    ///
    /// A `Result` containing a `WebsocketStreams` instance if the connection is successful,
    /// or an error if the connection fails.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the connection fails.
    ///
    /// # Examples
    ///
    ///
    /// let handle = `WebsocketStreamsHandle::new(configuration)`;
    /// let streams = handle.connect().await?;
    ///
    pub async fn connect(&self) -> anyhow::Result<WebsocketStreams> {
        self.connect_with_config(Default::default()).await
    }

    /// Connects to a WebSocket stream with a custom configuration.
    ///
    /// # Arguments
    ///
    /// * `cfg` - A configuration object specifying connection details for the WebSocket stream.
    ///
    /// # Returns
    ///
    /// A `Result` containing a `WebsocketStreams` instance if the connection is successful,
    /// or an error if the connection fails.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the connection fails.
    ///
    /// # Examples
    ///
    ///
    /// let handle = `WebsocketStreamsHandle::new(configuration)`;
    /// let `custom_config` = `WebsocketStreamsConnectConfig::default()`;
    /// let streams = `handle.connect_with_config(custom_config).await`?;
    ///
    pub async fn connect_with_config(
        &self,
        cfg: WebsocketStreamsConnectConfig,
    ) -> anyhow::Result<WebsocketStreams> {
        WebsocketStreams::connect(self.configuration.clone(), cfg.streams, cfg.mode).await
    }

    /// Connects one independent USD-M client to exactly one generated route.
    ///
    /// The client owns one `Single` connection slot and starts with no URL
    /// subscriptions. Public and market callers can then use confirmed routed
    /// JSON controls; private callers can use the confirmed user-data flow.
    /// Each call returns an independent client and can be closed with its
    /// existing [`WebsocketStreams::disconnect`] method.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the exact scoped connection fails.
    pub async fn connect_scope(
        &self,
        scope: UsdMStreamConnectionScope,
    ) -> anyhow::Result<WebsocketStreams> {
        WebsocketStreams::connect_scope(self.configuration.clone(), scope).await
    }
}

#[cfg(test)]
mod tests {
    use std::sync::Arc;

    use futures::StreamExt;
    use tokio::net::TcpListener;
    use tokio::sync::{
        mpsc::{UnboundedReceiver, unbounded_channel},
        oneshot,
    };
    use tokio::time::{Duration, timeout};
    use tokio_tungstenite::{
        accept_hdr_async,
        tungstenite::handshake::server::{Request, Response},
    };

    use crate::common::config::{
        ConfigurationWebsocketStreams, RawFrameObserver, WebsocketLifecycleEvent,
    };
    use crate::models::RoutedStreamScope;

    use super::*;

    type OpenObservation = (String, u64, Option<String>);

    async fn scoped_test_handle(
        expected_connections: usize,
    ) -> (
        WebsocketStreamsHandle,
        UnboundedReceiver<String>,
        UnboundedReceiver<OpenObservation>,
    ) {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let (path_sender, path_receiver) = unbounded_channel();
        tokio::spawn(async move {
            for _ in 0..expected_connections {
                let (stream, _) = listener.accept().await.unwrap();
                let sender = path_sender.clone();
                let websocket =
                    accept_hdr_async(stream, move |request: &Request, response: Response| {
                        sender.send(request.uri().path().to_string()).unwrap();
                        Ok(response)
                    })
                    .await
                    .unwrap();
                tokio::spawn(async move {
                    let mut websocket = websocket;
                    while websocket.next().await.is_some() {}
                });
            }
        });

        let (open_sender, open_receiver) = unbounded_channel();
        let observer = RawFrameObserver::new_context(|_| {}).with_lifecycle(move |context| {
            if context.event == WebsocketLifecycleEvent::Open {
                open_sender
                    .send((
                        context.connection_id.to_string(),
                        context.session_generation,
                        context.path_scope.map(str::to_string),
                    ))
                    .unwrap();
            }
        });
        let configuration = ConfigurationWebsocketStreams::builder()
            .ws_url(format!("ws://{address}"))
            .raw_frame_observer(observer)
            .build()
            .unwrap();
        (
            WebsocketStreamsHandle::new(configuration),
            path_receiver,
            open_receiver,
        )
    }

    async fn assert_routed_scope_does_not_reconnect(scope: UsdMStreamConnectionScope) {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let (drop_sender, drop_receiver) = oneshot::channel();
        let server = tokio::spawn(async move {
            let (stream, _) = listener.accept().await.unwrap();
            let websocket = accept_hdr_async(stream, |_request: &Request, response: Response| {
                Ok(response)
            })
            .await
            .unwrap();
            drop_receiver.await.unwrap();
            drop(websocket);

            // The historical SDK policy would attempt another handshake after
            // the configured 10 ms reconnect delay.
            timeout(Duration::from_millis(250), listener.accept())
                .await
                .is_ok()
        });

        let (lifecycle_sender, mut lifecycle_receiver) = unbounded_channel();
        let observer = RawFrameObserver::new_context(|_| {}).with_lifecycle(move |context| {
            let _ = lifecycle_sender.send(context.event);
        });
        let configuration = ConfigurationWebsocketStreams::builder()
            .ws_url(format!("ws://{address}"))
            .reconnect_delay(10_u64)
            .raw_frame_observer(observer)
            .build()
            .unwrap();
        let client = WebsocketStreamsHandle::new(configuration)
            .connect_scope(scope)
            .await
            .unwrap();
        assert!(!client.sdk_manages_session_replacement());
        let initial = client.connection_identity().unwrap();
        assert_eq!(
            lifecycle_receiver.recv().await,
            Some(WebsocketLifecycleEvent::Open)
        );

        drop_sender.send(()).unwrap();
        timeout(Duration::from_secs(1), async {
            loop {
                let event = lifecycle_receiver
                    .recv()
                    .await
                    .expect("transport lifecycle ended before disconnect evidence");
                if matches!(
                    event,
                    WebsocketLifecycleEvent::Close { .. }
                        | WebsocketLifecycleEvent::ReadError
                        | WebsocketLifecycleEvent::StreamEnded
                ) {
                    break;
                }
            }
        })
        .await
        .expect("caller-managed route did not observe server disconnect");

        assert!(
            !server.await.unwrap(),
            "routed exact client attempted an SDK-managed reconnect"
        );
        assert_eq!(client.connection_identity().unwrap(), initial);
        assert!(!client.is_connected().await);
        assert!(lifecycle_receiver.try_recv().is_err());
        client.disconnect().await.unwrap();
    }

    #[tokio::test]
    async fn exact_scope_opens_one_route_and_exposes_matching_identity() {
        let (handle, mut paths, mut opens) = scoped_test_handle(3).await;

        let public = handle
            .connect_scope(UsdMStreamConnectionScope::Public)
            .await
            .unwrap();
        assert_eq!(paths.recv().await.as_deref(), Some("/public/stream"));
        let public_identity = public.connection_identity().unwrap();
        assert_eq!(
            opens.recv().await.unwrap(),
            (
                public_identity.connection_id.clone(),
                public_identity.session_generation,
                Some("public".to_string())
            )
        );
        assert_eq!(public_identity.scope, UsdMStreamConnectionScope::Public);
        assert!(!public.sdk_manages_session_replacement());
        assert_eq!(public.renewal_enqueue_count(), 0);
        let public_target = public.routed_target().unwrap();
        assert_eq!(public_target.connection_id, public_identity.connection_id);
        assert_eq!(
            public_target.session_generation,
            public_identity.session_generation
        );
        assert_eq!(public_target.path_scope, RoutedStreamScope::Public);

        let market = handle
            .connect_scope(UsdMStreamConnectionScope::Market)
            .await
            .unwrap();
        assert_eq!(paths.recv().await.as_deref(), Some("/market/stream"));
        let market_identity = market.connection_identity().unwrap();
        assert_eq!(
            opens.recv().await.unwrap(),
            (
                market_identity.connection_id.clone(),
                market_identity.session_generation,
                Some("market".to_string())
            )
        );
        assert_eq!(market_identity.scope, UsdMStreamConnectionScope::Market);
        assert!(!market.sdk_manages_session_replacement());
        assert_eq!(market.renewal_enqueue_count(), 0);
        assert_eq!(
            market.routed_target().unwrap().path_scope,
            RoutedStreamScope::Market
        );

        let private = handle
            .connect_scope(UsdMStreamConnectionScope::Private)
            .await
            .unwrap();
        assert_eq!(paths.recv().await.as_deref(), Some("/private/stream"));
        let private_identity = private.connection_identity().unwrap();
        assert_eq!(private_identity.scope, UsdMStreamConnectionScope::Private);
        assert!(private.sdk_manages_session_replacement());
        assert_eq!(private.renewal_enqueue_count(), 1);
        assert_eq!(
            opens.recv().await.unwrap(),
            (
                private_identity.connection_id,
                private_identity.session_generation,
                Some("private".to_string())
            )
        );
        assert!(private.routed_target().is_none());
        assert!(paths.try_recv().is_err());

        public.disconnect().await.unwrap();
        market.disconnect().await.unwrap();
        private.disconnect().await.unwrap();
    }

    #[tokio::test]
    async fn routed_exact_scopes_wait_for_caller_managed_replacement() {
        assert_routed_scope_does_not_reconnect(UsdMStreamConnectionScope::Public).await;
        assert_routed_scope_does_not_reconnect(UsdMStreamConnectionScope::Market).await;
    }

    #[tokio::test]
    async fn routed_exact_scopes_do_not_enqueue_sdk_renewal() {
        let (handle, mut paths, mut opens) = scoped_test_handle(4).await;
        let public = handle
            .connect_scope(UsdMStreamConnectionScope::Public)
            .await
            .unwrap();
        let market = handle
            .connect_scope(UsdMStreamConnectionScope::Market)
            .await
            .unwrap();
        let mut opened_paths = vec![paths.recv().await.unwrap(), paths.recv().await.unwrap()];
        opened_paths.sort_unstable();
        assert_eq!(opened_paths, vec!["/market/stream", "/public/stream"]);
        assert!(opens.recv().await.is_some());
        assert!(opens.recv().await.is_some());
        let public_identity = public.connection_identity().unwrap();
        let market_identity = market.connection_identity().unwrap();
        assert_eq!(public.renewal_enqueue_count(), 0);
        assert_eq!(market.renewal_enqueue_count(), 0);
        assert!(opens.try_recv().is_err());
        assert!(paths.try_recv().is_err());
        assert_eq!(public.connection_identity().unwrap(), public_identity);
        assert_eq!(market.connection_identity().unwrap(), market_identity);
        public.disconnect().await.unwrap();
        market.disconnect().await.unwrap();
    }

    #[tokio::test]
    async fn private_exact_scope_retains_sdk_managed_reconnect() {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let (drop_sender, drop_receiver) = oneshot::channel();
        let (path_sender, mut path_receiver) = unbounded_channel();
        let server = tokio::spawn(async move {
            let (first_stream, _) = listener.accept().await.unwrap();
            let first_path_sender = path_sender.clone();
            let first = accept_hdr_async(
                first_stream,
                move |request: &Request, response: Response| {
                    first_path_sender
                        .send(request.uri().path().to_string())
                        .unwrap();
                    Ok(response)
                },
            )
            .await
            .unwrap();
            drop_receiver.await.unwrap();
            drop(first);

            let (second_stream, _) = timeout(Duration::from_secs(1), listener.accept())
                .await
                .expect("private exact client did not reconnect")
                .unwrap();
            let second = accept_hdr_async(
                second_stream,
                move |request: &Request, response: Response| {
                    path_sender.send(request.uri().path().to_string()).unwrap();
                    Ok(response)
                },
            )
            .await
            .unwrap();
            let mut second = second;
            while second.next().await.is_some() {}
        });

        let (open_sender, mut open_receiver) = unbounded_channel();
        let observer = RawFrameObserver::new_context(|_| {}).with_lifecycle(move |context| {
            if context.event == WebsocketLifecycleEvent::Open {
                let _ = open_sender.send((
                    context.connection_id.to_string(),
                    context.session_generation,
                    context.path_scope.map(str::to_string),
                ));
            }
        });
        let configuration = ConfigurationWebsocketStreams::builder()
            .ws_url(format!("ws://{address}"))
            .reconnect_delay(10_u64)
            .raw_frame_observer(observer)
            .build()
            .unwrap();
        let private = WebsocketStreamsHandle::new(configuration)
            .connect_scope(UsdMStreamConnectionScope::Private)
            .await
            .unwrap();
        assert!(private.sdk_manages_session_replacement());
        assert_eq!(
            path_receiver.recv().await.as_deref(),
            Some("/private/stream")
        );
        let first_open = open_receiver.recv().await.unwrap();
        drop_sender.send(()).unwrap();
        assert_eq!(
            timeout(Duration::from_secs(1), path_receiver.recv())
                .await
                .unwrap()
                .as_deref(),
            Some("/private/stream")
        );
        let second_open = timeout(Duration::from_secs(1), open_receiver.recv())
            .await
            .unwrap()
            .unwrap();
        assert_eq!(second_open.0, first_open.0);
        assert_eq!(second_open.1, first_open.1 + 1);
        assert_eq!(second_open.2.as_deref(), Some("private"));
        assert_eq!(
            private.connection_identity().unwrap().session_generation,
            second_open.1
        );

        private.disconnect().await.unwrap();
        timeout(Duration::from_secs(1), server)
            .await
            .expect("private mock server did not observe terminal disconnect")
            .unwrap();
    }

    #[tokio::test]
    async fn generic_client_retains_sdk_managed_recovery_mode() {
        let (handle, mut paths, mut opens) = scoped_test_handle(3).await;
        let generic = handle.connect().await.unwrap();
        assert!(generic.sdk_manages_session_replacement());

        let mut opened_paths = Vec::new();
        for _ in 0..3 {
            opened_paths.push(paths.recv().await.unwrap());
            assert!(opens.recv().await.is_some());
        }
        opened_paths.sort_unstable();
        assert_eq!(
            opened_paths,
            vec!["/market/stream", "/private/stream", "/public/stream"]
        );
        generic.disconnect().await.unwrap();
    }

    #[tokio::test]
    async fn exact_scope_clients_are_independent_disconnect_domains() {
        let (handle, mut paths, mut opens) = scoped_test_handle(2).await;
        let public = handle
            .connect_scope(UsdMStreamConnectionScope::Public)
            .await
            .unwrap();
        let market = handle
            .connect_scope(UsdMStreamConnectionScope::Market)
            .await
            .unwrap();
        let mut opened = vec![paths.recv().await.unwrap(), paths.recv().await.unwrap()];
        opened.sort_unstable();
        assert_eq!(opened, vec!["/market/stream", "/public/stream"]);
        assert_ne!(
            public.connection_identity().unwrap().connection_id,
            market.connection_identity().unwrap().connection_id
        );
        let first_open = opens.recv().await.unwrap();
        let second_open = opens.recv().await.unwrap();
        assert_ne!(first_open.0, second_open.0);
        assert!(public.is_connected().await);
        assert!(market.is_connected().await);

        let public_runtime = public.runtime_weak();
        assert_eq!(public.installed_handler_count().await, 1);
        assert_eq!(public.installed_writer_count().await, 1);
        assert_eq!(public.pending_stream_subscription_count().await, 0);
        assert!(public.registered_background_task_count() >= 4);

        public.disconnect().await.unwrap();
        assert!(!public.is_connected().await);
        assert!(market.is_connected().await);
        assert_eq!(public.installed_handler_count().await, 0);
        assert_eq!(public.installed_writer_count().await, 0);
        assert_eq!(public.pending_stream_subscription_count().await, 0);
        assert_eq!(public.registered_background_task_count(), 0);
        drop(public);
        assert!(public_runtime.upgrade().is_none());

        market.disconnect().await.unwrap();
        assert!(!market.is_connected().await);
    }

    #[tokio::test]
    async fn failed_exact_scope_handshake_releases_observer_and_transport_graph() {
        let listener = TcpListener::bind("127.0.0.1:0").await.unwrap();
        let address = listener.local_addr().unwrap();
        let server = tokio::spawn(async move {
            let (stream, _) = listener.accept().await.unwrap();
            drop(stream);
        });

        let observer_owner = Arc::new(());
        let observer_owner_weak = Arc::downgrade(&observer_owner);
        let observer_capture = Arc::clone(&observer_owner);
        let observer = RawFrameObserver::new_context(move |_| {
            let _ = &observer_capture;
        });
        let configuration = ConfigurationWebsocketStreams::builder()
            .ws_url(format!("ws://{address}"))
            .raw_frame_observer(observer)
            .build()
            .unwrap();
        let handle = WebsocketStreamsHandle::new(configuration);

        assert!(
            handle
                .connect_scope(UsdMStreamConnectionScope::Public)
                .await
                .is_err()
        );
        server.await.unwrap();
        drop(handle);
        drop(observer_owner);
        tokio::task::yield_now().await;
        assert!(observer_owner_weak.upgrade().is_none());
    }

    #[tokio::test]
    async fn cancelled_exact_disconnect_cannot_cancel_terminal_cleanup_owner() {
        let (handle, mut paths, mut opens) = scoped_test_handle(1).await;
        let client = Arc::new(
            handle
                .connect_scope(UsdMStreamConnectionScope::Public)
                .await
                .unwrap(),
        );
        assert_eq!(paths.recv().await.as_deref(), Some("/public/stream"));
        assert!(opens.recv().await.is_some());

        let runtime = client.runtime_weak();
        let state_guard = client.lock_first_connection_state().await;
        let disconnect = {
            let client = Arc::clone(&client);
            tokio::spawn(async move { client.disconnect().await })
        };
        timeout(Duration::from_secs(1), async {
            while !client.terminal_shutdown_started() {
                tokio::task::yield_now().await;
            }
        })
        .await
        .expect("terminal cleanup owner did not start");

        disconnect.abort();
        assert!(disconnect.await.unwrap_err().is_cancelled());
        drop(state_guard);
        drop(client);

        timeout(Duration::from_secs(1), async {
            while runtime.upgrade().is_some() {
                tokio::task::yield_now().await;
            }
        })
        .await
        .expect("detached terminal cleanup retained the SDK runtime graph");
    }
}
