/*
 * Futures (USDⓈ-M) WebSocket Market Streams
 *
 * Access market data, manage accounts, and trade USDⓈ-M perpetual futures.
 *
 * The version of the OpenAPI document: 1.0.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

#![allow(unused_imports)]
use serde_json::Value;
use std::{
    sync::{Arc, atomic::Ordering},
    time::Duration,
};
use tokio::spawn;

use crate::common::config::ConfigurationWebsocketStreams;
use crate::common::errors::StreamSubscriptionError;
use crate::common::websocket::{
    Subscription, WebsocketBase, WebsocketStream, WebsocketStreams as WebsocketStreamsBase,
    create_stream_handler, create_stream_handler_confirmed,
};
use crate::models::{
    RoutedStreamScope, RoutedStreamTarget, StreamId, StreamSubscriptionAck,
    StreamSubscriptionEvent, WebsocketEvent, WebsocketMode,
};

mod apis;
mod handle;
mod models;

pub use apis::*;
pub use handle::*;
pub use models::*;

const HAS_TIME_UNIT: bool = false;
const USER_DATA_SUBSCRIPTION_ACK_TIMEOUT: Duration = Duration::from_secs(10);

/// One generated USD-M WebSocket route owned by an exact stream client.
///
/// The closed enum prevents arbitrary paths, query strings, or credentials
/// from entering connection selection. Each [`WebsocketStreamsHandle::connect_scope`]
/// call creates one independent client with one physical connection slot.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum UsdMStreamConnectionScope {
    Public,
    Market,
    Private,
}

impl UsdMStreamConnectionScope {
    fn as_path_scope(self) -> &'static str {
        match self {
            Self::Public => "public",
            Self::Market => "market",
            Self::Private => "private",
        }
    }

    fn routed_scope(self) -> Option<RoutedStreamScope> {
        match self {
            Self::Public => Some(RoutedStreamScope::Public),
            Self::Market => Some(RoutedStreamScope::Market),
            Self::Private => None,
        }
    }
}

/// Read-only identity of the sole physical slot owned by an exact-scope client.
///
/// `connection_id` remains stable across reconnects; `session_generation`
/// advances for each newly opened physical session.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct UsdMStreamConnectionIdentity {
    pub connection_id: String,
    pub session_generation: u64,
    pub scope: UsdMStreamConnectionScope,
}

pub struct WebsocketStreams {
    websocket_streams_base: Arc<WebsocketStreamsBase>,
    market_api_client: MarketApiClient,
    public_api_client: PublicApiClient,
    connection_scope: Option<UsdMStreamConnectionScope>,
}

impl WebsocketStreams {
    pub(crate) async fn connect(
        config: ConfigurationWebsocketStreams,
        streams: Vec<String>,
        mode: Option<WebsocketMode>,
    ) -> anyhow::Result<Self> {
        let mut cfg = config;
        if let Some(m) = mode {
            cfg.mode = m;
        }

        if !HAS_TIME_UNIT {
            cfg.time_unit = None;
        }

        let websocket_streams_base = WebsocketStreamsBase::new(
            cfg,
            vec![],
            vec![
                "market".to_string(),
                "public".to_string(),
                "private".to_string(),
            ],
        );

        websocket_streams_base.clone().connect(streams).await?;

        Ok(Self::from_base(websocket_streams_base, None))
    }

    pub(crate) async fn connect_scope(
        mut config: ConfigurationWebsocketStreams,
        scope: UsdMStreamConnectionScope,
    ) -> anyhow::Result<Self> {
        config.mode = WebsocketMode::Single;
        if !HAS_TIME_UNIT {
            config.time_unit = None;
        }
        let websocket_streams_base =
            WebsocketStreamsBase::new(config, vec![], vec![scope.as_path_scope().to_string()]);
        if matches!(
            scope,
            UsdMStreamConnectionScope::Public | UsdMStreamConnectionScope::Market
        ) {
            // The connector contract owns retry timing, silence recovery and
            // desired-set replay for routed market-data sessions. Private and
            // generic SDK clients retain the SDK's historical recovery policy.
            websocket_streams_base
                .common
                .use_caller_managed_session_replacement();
        }
        if let Err(error) = websocket_streams_base.clone().connect(Vec::new()).await {
            // `connect` installs the generated handler before the handshake.
            // A failed handshake therefore needs the same terminal cleanup as
            // an explicitly retired exact-scope client; otherwise the handler
            // and transport workers retain the entire base graph.
            let _ = websocket_streams_base.terminal_shutdown().await;
            return Err(error.into());
        }

        Ok(Self::from_base(websocket_streams_base, Some(scope)))
    }

    fn from_base(
        websocket_streams_base: Arc<WebsocketStreamsBase>,
        connection_scope: Option<UsdMStreamConnectionScope>,
    ) -> Self {
        Self {
            websocket_streams_base: websocket_streams_base.clone(),
            market_api_client: MarketApiClient::new(websocket_streams_base.clone()),
            public_api_client: PublicApiClient::new(websocket_streams_base.clone()),
            connection_scope,
        }
    }

    /// Returns the current physical identity for an exact-scope client.
    ///
    /// Generic clients created by [`WebsocketStreamsHandle::connect`] return
    /// `None`, as do exact clients before their first physical session opens.
    #[must_use]
    pub fn connection_identity(&self) -> Option<UsdMStreamConnectionIdentity> {
        let scope = self.connection_scope?;
        let (connection_id, session_generation) =
            self.websocket_streams_base.single_connection_identity()?;
        (session_generation != 0).then_some(UsdMStreamConnectionIdentity {
            connection_id,
            session_generation,
            scope,
        })
    }

    /// Returns an exact routed target for public/market JSON controls.
    ///
    /// Private exact-scope clients return `None`; use
    /// [`Self::connection_identity`] to correlate their confirmed user-data
    /// flow with lifecycle observations.
    #[must_use]
    pub fn routed_target(&self) -> Option<RoutedStreamTarget> {
        let identity = self.connection_identity()?;
        let path_scope = identity.scope.routed_scope()?;
        Some(RoutedStreamTarget::new(
            identity.connection_id,
            identity.session_generation,
            path_scope,
        ))
    }

    /// Subscribes to WebSocket events with a provided callback function.
    ///
    /// # Arguments
    ///
    /// * `callback` - A mutable function that takes a `WebsocketEvent` and is `Send` and `'static`.
    ///
    /// # Returns
    ///
    /// A `Subscription` that can be used to manage the event subscription.
    ///
    /// # Security
    ///
    /// [`WebsocketEvent::Message`] is an explicit raw-frame escape hatch and
    /// can contain private listen keys or server text that repeats them. Do not
    /// log it verbatim. Use [`Self::subscribe_on_stream_subscription_events`]
    /// for redacted subscription lifecycle diagnostics.
    ///
    /// # Examples
    ///
    ///
    /// let subscription = `websocket_streams.subscribe_on_ws_events(|event`| {
    ///     // Handle WebSocket event
    /// });
    ///
    pub fn subscribe_on_ws_events<F>(&self, callback: F) -> Subscription
    where
        F: FnMut(WebsocketEvent) + Send + 'static,
    {
        let base = Arc::clone(&self.websocket_streams_base);
        base.common.events.subscribe(callback)
    }

    /// Unsubscribes from WebSocket events for a given `Subscription`.
    ///
    /// # Arguments
    ///
    /// * `subscription` - The `Subscription` to unsubscribe from WebSocket events.
    ///
    /// # Examples
    ///
    ///
    /// let subscription = `websocket_streams.subscribe_on_ws_events(|event`| {
    ///     // Handle WebSocket event
    /// });
    /// `websocket_streams.unsubscribe_from_ws_events(subscription)`;
    ///
    pub fn unsubscribe_from_ws_events(&self, subscription: Subscription) {
        subscription.unsubscribe();
    }

    /// Subscribes to correlated JSON stream-subscription outcomes for
    /// diagnostics. Delivery is asynchronous and is not an ordered ingress
    /// gate relative to raw frames. Configure a synchronous
    /// [`crate::common::config::StreamSubscriptionObserver`] for that purpose.
    /// Events never contain stream parameters or listen keys.
    pub fn subscribe_on_stream_subscription_events<F>(&self, callback: F) -> Subscription
    where
        F: FnMut(StreamSubscriptionEvent) + Send + 'static,
    {
        self.websocket_streams_base
            .subscribe_on_stream_subscription_events(callback)
    }

    /// Confirms a live JSON `SUBSCRIBE` on one exact `/public` or `/market`
    /// physical session.
    ///
    /// Binance requires an unsigned integer request `id` and acknowledges the
    /// exact request with `{ "result": null, "id": ... }`. Topics are sorted
    /// and deduplicated before encoding. The caller supplies and owns the
    /// monotonically increasing `request_id`; the SDK never substitutes a
    /// random value.
    ///
    /// This primitive does not register SDK desired-stream ownership and does
    /// not replay subscriptions after reconnect. Connect with an empty initial
    /// stream list, observe routed `Open` lifecycle events, then reissue the
    /// application-owned desired set against each new [`RoutedStreamTarget`].
    /// This prevents URL subscriptions and JSON controls from competing for
    /// initial or reconnect ownership.
    ///
    /// See the official [live subscription
    /// protocol](https://developers.binance.com/en/docs/products/derivatives-trading-usds-futures/websocket-market-streams/Live-Subscribing-Unsubscribing-to-streams)
    /// and [routed endpoint
    /// migration](https://developers.binance.com/en/docs/products/derivatives-trading-usds-futures/websocket-market-streams/Important-WebSocket-Change-Notice).
    ///
    /// # Errors
    ///
    /// Returns a redacted [`StreamSubscriptionError`] for stale targets,
    /// dispatch failures, exact correlated rejects, protocol violations,
    /// timeout, disconnect, or physical-session replacement.
    pub async fn subscribe_routed_confirmed(
        &self,
        target: RoutedStreamTarget,
        topics: Vec<String>,
        request_id: u32,
        ack_timeout: Duration,
    ) -> Result<StreamSubscriptionAck, StreamSubscriptionError> {
        self.websocket_streams_base
            .subscribe_routed_confirmed(target, topics, request_id, ack_timeout)
            .await
    }

    /// Confirms a live JSON `UNSUBSCRIBE` on one exact `/public` or `/market`
    /// physical session.
    ///
    /// The same caller-owned desired-set and monotonically increasing numeric
    /// request-id rules as [`Self::subscribe_routed_confirmed`] apply. The SDK
    /// sends topics in deterministic sorted order and does not mutate or replay
    /// application subscription ownership.
    ///
    /// # Errors
    ///
    /// Returns a redacted [`StreamSubscriptionError`] under the exact
    /// correlation and terminal-outcome rules described by
    /// [`Self::subscribe_routed_confirmed`].
    pub async fn unsubscribe_routed_confirmed(
        &self,
        target: RoutedStreamTarget,
        topics: Vec<String>,
        request_id: u32,
        ack_timeout: Duration,
    ) -> Result<StreamSubscriptionAck, StreamSubscriptionError> {
        self.websocket_streams_base
            .unsubscribe_routed_confirmed(target, topics, request_id, ack_timeout)
            .await
    }

    /// Disconnects the WebSocket connection.
    ///
    /// # Returns
    ///
    /// A `Result` indicating whether the disconnection was successful.
    /// Returns an error if the disconnection fails.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the connection fails.
    ///
    /// # Examples
    ///
    ///
    /// let `websocket_streams` = `WebSocketStreams::new`(...);
    /// `websocket_streams.disconnect().await`?;
    ///
    pub async fn disconnect(&self) -> anyhow::Result<()> {
        if self.connection_scope.is_some() {
            // Exact-scope clients are independently owned transport domains
            // with no public reconnect operation. Their existing disconnect
            // contract is therefore terminal: delayed SDK renewal/reconnect
            // work must not reopen a retired route.
            self.websocket_streams_base
                .terminal_shutdown()
                .await
                .map_err(anyhow::Error::msg)
        } else {
            self.websocket_streams_base
                .disconnect()
                .await
                .map_err(anyhow::Error::msg)
        }
    }

    #[cfg(test)]
    fn runtime_weak(&self) -> std::sync::Weak<crate::common::websocket::WebsocketCommon> {
        Arc::downgrade(&self.websocket_streams_base.common)
    }

    #[cfg(test)]
    fn sdk_manages_session_replacement(&self) -> bool {
        self.websocket_streams_base
            .common
            .sdk_manages_session_replacement()
    }

    #[cfg(test)]
    fn renewal_enqueue_count(&self) -> u64 {
        self.websocket_streams_base.common.renewal_enqueue_count()
    }

    #[cfg(test)]
    fn registered_background_task_count(&self) -> usize {
        self.websocket_streams_base
            .common
            .registered_background_task_count()
    }

    #[cfg(test)]
    async fn installed_handler_count(&self) -> usize {
        self.websocket_streams_base
            .common
            .installed_handler_count()
            .await
    }

    #[cfg(test)]
    async fn installed_writer_count(&self) -> usize {
        self.websocket_streams_base
            .common
            .installed_writer_count()
            .await
    }

    #[cfg(test)]
    async fn pending_stream_subscription_count(&self) -> usize {
        self.websocket_streams_base
            .common
            .pending_stream_subscription_count()
            .await
    }

    #[cfg(test)]
    fn terminal_shutdown_started(&self) -> bool {
        self.websocket_streams_base
            .common
            .terminal_shutdown_started()
    }

    #[cfg(test)]
    async fn lock_first_connection_state(
        &self,
    ) -> tokio::sync::MutexGuard<'_, crate::common::websocket::WebsocketConnectionState> {
        self.websocket_streams_base
            .common
            .lock_first_connection_state()
            .await
    }

    /// Checks if the WebSocket connection is currently active.
    ///
    /// # Returns
    ///
    /// A `bool` indicating whether the WebSocket connection is established and connected.
    ///
    /// # Examples
    ///
    ///
    /// let `is_active` = `websocket_streams.is_connected().await`;
    /// if `is_active` {
    ///     // WebSocket connection is active
    /// }
    ///
    pub async fn is_connected(&self) -> bool {
        self.websocket_streams_base.is_connected().await
    }

    /// Sends a ping to the WebSocket server to maintain the connection.
    ///
    /// # Examples
    ///
    ///
    /// `websocket_streams.ping_server().await`;
    ///
    ///
    /// This method sends a ping request to the WebSocket server to keep the connection alive
    /// and check the server's responsiveness.
    pub async fn ping_server(&self) {
        self.websocket_streams_base.ping_server().await;
    }

    /// Subscribes to specified WebSocket streams.
    ///
    /// # Arguments
    ///
    /// * `streams` - A vector of stream names to subscribe to
    /// * `id` - An optional identifier for the subscription request
    ///
    /// # Examples
    ///
    ///
    /// `websocket_streams.subscribe(vec`!["`btcusdt@trade".to_string()`], None).await;
    ///
    ///
    /// This method initiates an asynchronous subscription to the specified WebSocket streams.
    /// The subscription is performed in a separate task using `spawn`.
    pub fn subscribe(&self, streams: Vec<String>, id: Option<String>) {
        let base = Arc::clone(&self.websocket_streams_base);
        spawn(async move { base.subscribe(streams, id.map(StreamId::from), None).await });
    }

    /// Unsubscribes from specified WebSocket streams.
    ///
    /// # Arguments
    ///
    /// * `streams` - A vector of stream names to unsubscribe from
    /// * `id` - An optional identifier for the unsubscription request
    ///
    /// # Examples
    ///
    ///
    /// `websocket_streams.unsubscribe(vec`!["`btcusdt@trade".to_string()`], None).await;
    ///
    ///
    /// This method initiates an asynchronous unsubscription from the specified WebSocket streams.
    /// The unsubscription is performed in a separate task using `spawn`.
    pub fn unsubscribe(&self, streams: Vec<String>, id: Option<String>) {
        let base = Arc::clone(&self.websocket_streams_base);
        spawn(async move {
            base.unsubscribe(streams, id.map(StreamId::from), None)
                .await;
        });
    }

    /// Checks if the current WebSocket stream is subscribed to a specific stream.
    ///
    /// # Arguments
    ///
    /// * `stream` - The name of the stream to check for subscription
    ///
    /// # Returns
    ///
    /// A boolean indicating whether the stream is currently subscribed
    ///
    /// # Examples
    ///
    ///
    /// let `is_subscribed` = `websocket_streams.is_subscribed("btcusdt@trade").await`;
    ///
    ///
    /// This method checks the subscription status of a specific WebSocket stream.
    pub async fn is_subscribed(&self, stream: &str) -> bool {
        self.websocket_streams_base.is_subscribed(stream).await
    }

    /// User Data Stream
    ///
    /// Establishes a WebSocket stream for user-specific data events.
    ///
    /// # Arguments
    ///
    /// - `listen_key`: A unique key for identifying the user's data stream
    /// - `id`: An optional identifier for the stream request
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<UserDataStreamEventsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream creation fails or if parsing the response encounters issues.
    ///
    /// # Examples
    ///
    ///
    /// let `user_stream` = `websocket_streams.user_data(listen_key`, None).await?;
    ///
    pub async fn user_data(
        &self,
        listen_key: String,
        id: Option<String>,
    ) -> anyhow::Result<Arc<WebsocketStream<UserDataStreamEventsResponse>>> {
        // Keep the generated source-level signature while complying with the
        // venue's unsigned-INT requirement. Decimal u32 strings are preserved;
        // UUID/hex or otherwise invalid legacy IDs are replaced by an unsigned
        // allocator value rather than sent as unsupported JSON strings.
        let request_id = id
            .as_deref()
            .and_then(|id| id.parse::<u32>().ok())
            .unwrap_or_else(|| self.websocket_streams_base.next_stream_request_id());
        let (stream, _) = self
            .user_data_confirmed(listen_key, request_id, USER_DATA_SUBSCRIPTION_ACK_TIMEOUT)
            .await
            .map_err(anyhow::Error::new)?;
        Ok(stream)
    }

    /// Subscribes to all events for one listen key and returns only after the
    /// exact numeric request has been acknowledged on the physical session
    /// identified by the returned context.
    ///
    /// The current Binance notice does not define the selected-events JSON item
    /// schema. This method therefore preserves the generated SDK's established
    /// all-events form, `params: [listen_key]`, and does not invent an extension.
    ///
    /// # Errors
    ///
    /// Returns a redacted [`StreamSubscriptionError`] when the numeric request
    /// cannot be dispatched or exactly acknowledged on its physical session.
    pub async fn user_data_confirmed(
        &self,
        listen_key: String,
        request_id: u32,
        ack_timeout: Duration,
    ) -> Result<
        (
            Arc<WebsocketStream<UserDataStreamEventsResponse>>,
            StreamSubscriptionAck,
        ),
        StreamSubscriptionError,
    > {
        create_stream_handler_confirmed::<UserDataStreamEventsResponse>(
            WebsocketBase::WebsocketStreams(self.websocket_streams_base.clone()),
            listen_key,
            request_id,
            ack_timeout,
            Some("private".to_string()),
        )
        .await
    }

    /// Aggregate Trade Streams
    ///
    /// The Aggregate Trade Streams push market trade information that is aggregated for fills with same price and taking side every 100 milliseconds. Only market trades will be aggregated, which means the insurance fund trades and ADL trades won't be aggregated.
    ///
    /// > **After CM migration**, the payload is appended with a new `st` field (`1` = UM, `2` = CM).
    ///
    /// Update Speed: 100ms
    ///
    /// Response Notes:
    /// - Retail Price Improvement(RPI) orders are aggregated into field q and without special tags to be distinguished.
    ///
    /// # Arguments
    ///
    /// - `params`: [`AggregateTradeStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::AggregateTradeStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#aggregate-trade-streams).
    ///
    pub async fn aggregate_trade_streams(
        &self,
        params: AggregateTradeStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::AggregateTradeStreamsResponse>>> {
        self.market_api_client.aggregate_trade_streams(params).await
    }

    /// All Market Liquidation Order Streams
    ///
    /// The All Liquidation Order Snapshot Streams push force liquidation order information for all symbols in the market. For each symbol，only the latest one liquidation order within 1000ms will be pushed as the snapshot. If no liquidation happens in the interval of 1000ms, no stream will be pushed.
    ///
    /// > **After CM migration**, this stream pushes the merged UM + CM universe (subscribable on both `fstream` and `dstream`); each payload is appended with a new `st` field (`1` = UM, `2` = CM) and a new `ps` field (pair symbol).
    ///
    /// Update Speed: 1000ms
    ///
    /// # Arguments
    ///
    /// - `params`: [`AllMarketLiquidationOrderStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::AllMarketLiquidationOrderStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#all-market-liquidation-order-streams).
    ///
    pub async fn all_market_liquidation_order_streams(
        &self,
        params: AllMarketLiquidationOrderStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::AllMarketLiquidationOrderStreamsResponse>>>
    {
        self.market_api_client
            .all_market_liquidation_order_streams(params)
            .await
    }

    /// All Market Mini Tickers Stream
    ///
    /// 24hr rolling window mini-ticker statistics for all symbols. These are NOT the statistics of the UTC day, but a 24hr rolling window from requestTime to 24hrs before. Note that only tickers that have changed will be present in the array.
    ///
    /// > **After CM migration**, this stream pushes the merged UM + CM universe (subscribable on both `fstream` and `dstream`); each payload is appended with a new `st` field (`1` = UM, `2` = CM) and a new `ps` field (pair symbol).
    ///
    /// Update Speed: 1000ms
    ///
    /// # Arguments
    ///
    /// - `params`: [`AllMarketMiniTickersStreamParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<Vec<models::AllMarketMiniTickersStreamResponseInner>>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#all-market-mini-tickers-stream).
    ///
    pub async fn all_market_mini_tickers_stream(
        &self,
        params: AllMarketMiniTickersStreamParams,
    ) -> anyhow::Result<Arc<WebsocketStream<Vec<models::AllMarketMiniTickersStreamResponseInner>>>>
    {
        self.market_api_client
            .all_market_mini_tickers_stream(params)
            .await
    }

    /// All Market Tickers Streams
    ///
    /// 24hr rolling window ticker statistics for all symbols. These are NOT the statistics of the UTC day, but a 24hr rolling window from requestTime to 24hrs before. Note that only tickers that have changed will be present in the array.
    ///
    /// > **After CM migration**, this stream pushes the merged UM + CM universe (subscribable on both `fstream` and `dstream`); each payload is appended with a new `st` field (`1` = UM, `2` = CM) and a new `ps` field (pair symbol).
    ///
    /// Update Speed: 1000ms
    ///
    /// # Arguments
    ///
    /// - `params`: [`AllMarketTickersStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<Vec<models::AllMarketTickersStreamsResponseInner>>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#all-market-tickers-streams).
    ///
    pub async fn all_market_tickers_streams(
        &self,
        params: AllMarketTickersStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<Vec<models::AllMarketTickersStreamsResponseInner>>>>
    {
        self.market_api_client
            .all_market_tickers_streams(params)
            .await
    }

    /// Multi-Assets Mode Asset Index
    ///
    /// Asset index price. Subscribe with `!assetIndex@arr` for all assets, or `<assetSymbol>@assetIndex` for a specific asset.
    ///
    /// > **CM-UM Integration (Effective 2026-06-30):** Renamed from *Multi-Assets Mode Asset Index*. The stream `!assetIndex@arr` now additionally pushes COIN-M settlement-asset price index entries (e.g., `BTCUSD`, `ETHUSD`, `BNBUSD`). The on-the-wire stream key is unchanged; existing subscriptions continue to work.
    ///
    /// Update Speed: 1s
    ///
    /// # Arguments
    ///
    /// - `params`: [`AssetIndexParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<Vec<models::AssetIndexResponseInner>>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#asset-index).
    ///
    pub async fn asset_index(
        &self,
        params: AssetIndexParams,
    ) -> anyhow::Result<Arc<WebsocketStream<Vec<models::AssetIndexResponseInner>>>> {
        self.market_api_client.asset_index(params).await
    }

    /// Composite Index Symbol Information Streams
    ///
    /// Composite index information for index symbols pushed every second.
    ///
    /// Update Speed: 1000ms
    ///
    /// # Arguments
    ///
    /// - `params`: [`CompositeIndexSymbolInformationStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::CompositeIndexSymbolInformationStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#composite-index-symbol-information-streams).
    ///
    pub async fn composite_index_symbol_information_streams(
        &self,
        params: CompositeIndexSymbolInformationStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::CompositeIndexSymbolInformationStreamsResponse>>>
    {
        self.market_api_client
            .composite_index_symbol_information_streams(params)
            .await
    }

    /// Continuous Contract Kline/Candlestick Streams
    ///
    /// Continuous Contract Kline/Candlestick Streams
    ///
    /// > **After CM migration**, both `fstream` and `dstream` may subscribe to either UM or CM symbols on this stream.
    ///
    /// Update Speed: 250ms
    ///
    /// # Arguments
    ///
    /// - `params`: [`ContinuousContractKlineCandlestickStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::ContinuousContractKlineCandlestickStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#continuous-contract-kline-candlestick-streams).
    ///
    pub async fn continuous_contract_kline_candlestick_streams(
        &self,
        params: ContinuousContractKlineCandlestickStreamsParams,
    ) -> anyhow::Result<
        Arc<WebsocketStream<models::ContinuousContractKlineCandlestickStreamsResponse>>,
    > {
        self.market_api_client
            .continuous_contract_kline_candlestick_streams(params)
            .await
    }

    /// Contract Info Stream
    ///
    /// `ContractInfo` stream pushes when contract info updates(listing/settlement/contract bracket update). bks field only shows up when bracket gets updated.
    ///
    /// > **After CM migration**, this stream pushes the merged UM + CM universe (subscribable on both `fstream` and `dstream`); each payload is appended with a new `st` field (`1` = UM, `2` = CM).
    ///
    /// Update Speed: Real-time
    ///
    /// # Arguments
    ///
    /// - `params`: [`ContractInfoStreamParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::ContractInfoStreamResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#contract-info-stream).
    ///
    pub async fn contract_info_stream(
        &self,
        params: ContractInfoStreamParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::ContractInfoStreamResponse>>> {
        self.market_api_client.contract_info_stream(params).await
    }

    /// Individual Symbol Mini Ticker Stream
    ///
    /// 24hr rolling window mini-ticker statistics for a single symbol. These are NOT the statistics of the UTC day, but a 24hr rolling window from requestTime to 24hrs before.
    ///
    /// > **After CM migration**, the payload is appended with a new `st` field (`1` = UM, `2` = CM) and a new `ps` field (pair symbol).
    ///
    /// Update Speed: 2s
    ///
    /// # Arguments
    ///
    /// - `params`: [`IndividualSymbolMiniTickerStreamParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::IndividualSymbolMiniTickerStreamResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#individual-symbol-mini-ticker-stream).
    ///
    pub async fn individual_symbol_mini_ticker_stream(
        &self,
        params: IndividualSymbolMiniTickerStreamParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::IndividualSymbolMiniTickerStreamResponse>>>
    {
        self.market_api_client
            .individual_symbol_mini_ticker_stream(params)
            .await
    }

    /// Individual Symbol Ticker Streams
    ///
    /// 24hr rolling window ticker statistics for a single symbol. These are NOT the statistics of the UTC day, but a 24hr rolling window from requestTime to 24hrs before.
    ///
    /// > **After CM migration**, the payload is appended with a new `st` field (`1` = UM, `2` = CM) and a new `ps` field (pair symbol).
    ///
    /// Update Speed: 2000ms
    ///
    /// # Arguments
    ///
    /// - `params`: [`IndividualSymbolTickerStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::IndividualSymbolTickerStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#individual-symbol-ticker-streams).
    ///
    pub async fn individual_symbol_ticker_streams(
        &self,
        params: IndividualSymbolTickerStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::IndividualSymbolTickerStreamsResponse>>> {
        self.market_api_client
            .individual_symbol_ticker_streams(params)
            .await
    }

    /// Kline/Candlestick Streams
    ///
    /// The Kline/Candlestick Stream push updates to the current klines/candlestick every 250 milliseconds (if existing).
    ///
    /// > **After CM migration**, both `fstream` and `dstream` may subscribe to either UM or CM symbols on this stream.
    ///
    /// Update Speed: 250ms
    ///
    /// # Arguments
    ///
    /// - `params`: [`KlineCandlestickStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::KlineCandlestickStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#kline-candlestick-streams).
    ///
    pub async fn kline_candlestick_streams(
        &self,
        params: KlineCandlestickStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::KlineCandlestickStreamsResponse>>> {
        self.market_api_client
            .kline_candlestick_streams(params)
            .await
    }

    /// Liquidation Order Streams
    ///
    /// The Liquidation Order Snapshot Streams push force liquidation order information for specific symbol. For each symbol，only the latest one liquidation order within 1000ms will be pushed as the snapshot. If no liquidation happens in the interval of 1000ms, no stream will be pushed.
    ///
    /// Update Speed: 1000ms
    ///
    /// # Arguments
    ///
    /// - `params`: [`LiquidationOrderStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::LiquidationOrderStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#liquidation-order-streams).
    ///
    pub async fn liquidation_order_streams(
        &self,
        params: LiquidationOrderStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::LiquidationOrderStreamsResponse>>> {
        self.market_api_client
            .liquidation_order_streams(params)
            .await
    }

    /// Mark Price Stream
    ///
    /// Mark price and funding rate for a single symbol pushed every 3 seconds or every second.
    ///
    /// > **After CM migration**, the payload is appended with a new `st` field (`1` = UM, `2` = CM); both `fstream` and `dstream` may subscribe to either UM or CM symbols on this stream.
    ///
    /// # Arguments
    ///
    /// - `params`: [`MarkPriceStreamParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::MarkPriceStreamResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#mark-price-stream).
    ///
    pub async fn mark_price_stream(
        &self,
        params: MarkPriceStreamParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::MarkPriceStreamResponse>>> {
        self.market_api_client.mark_price_stream(params).await
    }

    /// Mark Price Stream for All market
    ///
    /// Mark price and funding rate for all symbols pushed every 3 seconds or every second.
    ///
    /// **Note:**
    /// - `TradFi` symbols will be pushed through a seperate message.
    ///
    /// > **After CM migration**, the payload is appended with a new `st` field (`1` = UM, `2` = CM); both `fstream` and `dstream` may subscribe to either UM or CM symbols on this stream.
    ///
    /// Update Speed: 3000ms or 1000ms
    ///
    /// # Arguments
    ///
    /// - `params`: [`MarkPriceStreamForAllMarketParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<Vec<models::MarkPriceStreamForAllMarketResponseInner>>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#mark-price-stream-for-all-market).
    ///
    pub async fn mark_price_stream_for_all_market(
        &self,
        params: MarkPriceStreamForAllMarketParams,
    ) -> anyhow::Result<Arc<WebsocketStream<Vec<models::MarkPriceStreamForAllMarketResponseInner>>>>
    {
        self.market_api_client
            .mark_price_stream_for_all_market(params)
            .await
    }

    /// Trading Session Stream
    ///
    /// Trading session information for the underlying assets of `TradFi` Perpetual contracts, covering the U.S. equity market, Korean equity market, and the commodity market, is updated every second. Trading session information for different underlying markets is pushed in separate messages.
    ///
    /// **Event type:**
    ///
    /// - `EquityUpdate`: Session types for the U.S. equity market include "`PRE_MARKET`", "REGULAR", "`AFTER_MARKET`", "OVERNIGHT", and "`NO_TRADING`".
    /// - `CommodityUpdate`: Session types for the commodity market include "REGULAR" and "`NO_TRADING`".
    /// - `KR_EquityUpdate`: Session types for the Korean equity market include "REGULAR" and "`NO_TRADING`".
    ///
    /// Update Speed: 1s
    ///
    /// # Arguments
    ///
    /// - `params`: [`TradingSessionStreamParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::TradingSessionStreamResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/market#trading-session-stream).
    ///
    pub async fn trading_session_stream(
        &self,
        params: TradingSessionStreamParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::TradingSessionStreamResponse>>> {
        self.market_api_client.trading_session_stream(params).await
    }

    /// All Book Tickers Stream
    ///
    /// Pushes any update to the best bid or ask's price or quantity in real-time for all symbols.
    ///
    /// > **After CM migration**, this stream pushes the merged UM + CM universe (subscribable on both `fstream` and `dstream`); each payload is appended with a new `st` field (`1` = UM, `2` = CM) and a new `ps` field (pair symbol).
    ///
    /// Update Speed: 5s
    ///
    /// Response Notes:
    /// - Retail Price Improvement(RPI) orders are not visible and excluded in the response message.
    ///
    /// # Arguments
    ///
    /// - `params`: [`AllBookTickersStreamParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::AllBookTickersStreamResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/public#all-book-tickers-stream).
    ///
    pub async fn all_book_tickers_stream(
        &self,
        params: AllBookTickersStreamParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::AllBookTickersStreamResponse>>> {
        self.public_api_client.all_book_tickers_stream(params).await
    }

    /// Diff. Book Depth Streams
    ///
    /// Bids and asks, pushed every 250 milliseconds, 500 milliseconds, 100 milliseconds (if existing).
    ///
    /// > **After CM migration**, the payload is appended with a new `st` field (`1` = UM, `2` = CM) and a new `ps` field (pair symbol).
    ///
    /// Update Speed: 250ms, 500ms, 100ms
    ///
    /// Response Notes:
    /// - Retail Price Improvement(RPI) orders are not visible and excluded in the response message.
    ///
    /// # Arguments
    ///
    /// - `params`: [`DiffBookDepthStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::DiffBookDepthStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/public#diff-book-depth-streams).
    ///
    pub async fn diff_book_depth_streams(
        &self,
        params: DiffBookDepthStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::DiffBookDepthStreamsResponse>>> {
        self.public_api_client.diff_book_depth_streams(params).await
    }

    /// Individual Symbol Book Ticker Streams
    ///
    /// Pushes any update to the best bid or ask's price or quantity in real-time for a specified symbol.
    ///
    /// > **After CM migration**, the payload is appended with a new `st` field (`1` = UM, `2` = CM).
    ///
    /// Update Speed: Real-time
    ///
    /// Response Notes:
    /// Retail Price Improvement (RPI) orders are not visible and excluded in the response message.
    ///
    /// # Arguments
    ///
    /// - `params`: [`IndividualSymbolBookTickerStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::IndividualSymbolBookTickerStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/public#individual-symbol-book-ticker-streams).
    ///
    pub async fn individual_symbol_book_ticker_streams(
        &self,
        params: IndividualSymbolBookTickerStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::IndividualSymbolBookTickerStreamsResponse>>>
    {
        self.public_api_client
            .individual_symbol_book_ticker_streams(params)
            .await
    }

    /// Partial Book Depth Streams
    ///
    /// Top <levels> bids and asks
    ///
    /// > **After CM migration**, the payload is appended with a new `st` field (`1` = UM, `2` = CM) and a new `ps` field (pair symbol).
    ///
    /// Update Speed: 250ms or 500ms or 100ms
    ///
    /// Response Notes:
    /// Retail Price Improvement (RPI) orders are not visible and excluded in the response message.
    ///
    /// # Arguments
    ///
    /// - `params`: [`PartialBookDepthStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::PartialBookDepthStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/public#partial-book-depth-streams).
    ///
    pub async fn partial_book_depth_streams(
        &self,
        params: PartialBookDepthStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::PartialBookDepthStreamsResponse>>> {
        self.public_api_client
            .partial_book_depth_streams(params)
            .await
    }

    /// RPI Diff. Book Depth Streams
    ///
    /// Bids and asks including RPI orders, pushed every 500 milliseconds
    ///
    /// > **After CM migration**, the payload is appended with a new `st` field (`1` = UM, `2` = CM) and a new `ps` field (pair symbol).
    ///
    /// Update Speed: 500ms
    ///
    /// Response Notes:
    /// - RPI(Retail Price Improvement) orders are included and aggreated in the response message. When the quantity of a price level to be updated is equal to 0, it means either all quotations for this price have been filled/canceled, or the quantity of crossed RPI orders for this price are hidden
    ///
    /// # Arguments
    ///
    /// - `params`: [`RpiDiffBookDepthStreamsParams`]
    ///   The parameters for this operation.
    ///
    /// # Returns
    ///
    /// [`Arc<WebsocketStream<models::RpiDiffBookDepthStreamsResponse>>`] on success.
    ///
    /// # Errors
    ///
    /// Returns an [`anyhow::Error`] if the stream request fails, if parameters are invalid, or if parsing the response fails.
    ///
    ///
    /// For full API details, see the [Binance API Documentation](https://developers.binance.com/en/docs/catalog/core-trading-derivatives-trading-usd-s-m-futures/api/ws-streams/public#rpi-diff-book-depth-streams).
    ///
    pub async fn rpi_diff_book_depth_streams(
        &self,
        params: RpiDiffBookDepthStreamsParams,
    ) -> anyhow::Result<Arc<WebsocketStream<models::RpiDiffBookDepthStreamsResponse>>> {
        self.public_api_client
            .rpi_diff_book_depth_streams(params)
            .await
    }
}
